# Формат hex'ов: #FFFFFF и т.д либо другие форматы

# {player} - ник игрока
# {group} - название группы из LuckPerms

commands:
  - "lp user {player} parent add {group}"
#  - "msg {player} Вам выдали привилегию {group}"

database:
  type: H2
  path: "{pluginFolder}/database.db"

  # ---
  #
  # требуется если вам нужен MYSQL
  #
  # ---

  #url: "jdbc:mysql://localhost:3306/plugin"
  #username: "test"
  #password: "test"

messages:
  player_only: "&cДанная команда доступна только от игрока!"

  # {groups_count} - Количество доступных групп для выдачи
  list_response: "Вам доступно всего ({groups_count}):"

  # {prefix} - префикс группы
  # {group} - название группы из LuckPerms
  # {count} - количество возможных групп
  list_format: " &a- {prefix} &f(&7&o{group}&f)&r - &e{count}x"

  no_groups: "&7&oВозможно у пользователя нет групп которые он мог бы выдать, либо группа не найдена"
  no_gived_donate: "&cВаша привилегия не позволяет выдавать группы игрокам"
  no_gived_this_group: "&cВы не можете выдать эту группу игроку"
  no_entry_group: "&cВы не ввели группу!"
  no_found_group: "&cГруппа не найдена!"

  limit_gived_group: "&cВы исчерпали лимит выдачи данной группы!"

  # {permission} - какое право требуется
  no_permission: "&cУ вас недостаточно прав! {permission}"
  no_found_player: "&cИгрок не найден"

  help_response:
    - " "
    - "&bПравильное использование:"
    - " &e- &a/grant give <player> <group> &f- выдать группу"
    - " &e- &a/grant list &f- узнать возможные группы для выдачи"
    - " &e- &a/grant reload &f- Перезагрузить конфигурацию"
    - " "

  reload_config: "&cКонфигурация успешно перезагружена!"

groups:
  dragon:
    hero: 1
    povel: 2

notify:
  enable: false
  message:
    - " "
    - "Игрок &7{player} выдал донат {group} &7{gived_player}"
    - "Давайте поздравим его!"
    - " "
  sound:
    enable: true
    sound: ENTITY_PLAYER_LEVELUP
  actionbar:
    enable: true
    message: "&fИгрок {player} выдал донат игроку {gived_player}, смотри в чате!"